-- CREAR LA BASE DE DATOS
CREATE DATABASE IF NOT EXISTS gym;

-- USAR LA BBDD
USE gym;

-- CREAR TABLA USERS
CREATE TABLE IF NOT EXISTS users (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) UNIQUE NOT NULL,
	email VARCHAR(120) UNIQUE,
	age INT,
	fitness_goal VARCHAR(100),
	membership_type VARCHAR(50)
);

-- CREAR TABLA TRAINERS
CREATE TABLE IF NOT EXISTS trainers (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	speciality VARCHAR(100),
	experience_years INT,
	email VARCHAR(120) UNIQUE,
    phone VARCHAR(20)
);

-- CREAR TABLA WORKOUTS
CREATE TABLE IF NOT EXISTS workouts (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    difficulty VARCHAR(50),
    duration INT,
    description TEXT,
    trainer_id INT UNSIGNED,
    FOREIGN KEY (trainer_id) REFERENCES trainers(id)
);